openapi: 3.0.1
info:
  title: 항해 이커머스 Swagger
  description: |
    ### API 기능 소개
    - **쿠폰**
        - 쿠폰 발급
        - 보유 쿠폰 조회
    - **잔액**
        - 잔액 조회
        - 잔액 충전
    - **상품**
        - 상품 조회
        - 상품 목록 조회
    - **주문**
        - 주문 요청
        - 주문 결제 요청
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: CouponController
    description: 쿠폰
  - name: ProductController
    description: 상품
  - name: OrderController
    description: 주문
  - name: PaymentController
    description: 결제
  - name: BalanceController
    description: 잔액
paths:
  /api/v1/payments:
    post:
      tags:
        - PaymentController
      summary: 결제 요청
      description: 사용자 특정 주문에 대한 결제를 요청
      operationId: processPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRegisterV1'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /api/v1/orders:
    post:
      tags:
        - OrderController
      summary: 주문 요청
      description: 사용자 주문 요청
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRegisterV1'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /api/v1/coupons/issue:
    post:
      tags:
        - CouponController
      summary: 선착순 쿠폰 발급
      description: 쿠폰을 선착순으로 발급 한다.
      operationId: issueCoupon
      requestBody:
        description: 선착순 쿠폰 발급
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CouponRegisterV1'
        required: true
      responses:
        '200':
          description: 쿠폰 발급 성공
          content:
            application/json:
              schema:
                type: string
        '400':
          description: 잘못된 요청
          content:
            application/json: {}
  /api/v1/balance/charge:
    post:
      tags:
        - BalanceController
      summary: 잔액 충전
      description: 특정 사용자의 잔액을 충전합니다.
      operationId: chargeBalance
      requestBody:
        description: 잔액 충전을 위한 요청 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceRegisterV1'
        required: true
      responses:
        '200':
          description: 잔액 충전 성공
          content:
            application/json:
              schema:
                type: string
        '400':
          description: 잘못된 요청
          content:
            application/json: {

            }
  /api/v1/products:
    get:
      tags:
        - ProductController
      summary: 상품 목록 조회
      description: 상품을 조회한다.
      operationId: getProducts
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: name,asc
      responses:
        '200':
          description: 상품 목록 조회 성공
          content:
            application/json:
              schema:
                type: string
        '404':
          description: 상품을 찾을 수 없습니다.
          content:
            application/json: {}
  /api/v1/products/top:
    get:
      tags:
        - ProductController
      summary: 상위 상품 조회 요청
      description: 상위 상품 조회 정보를 조회한다.
      operationId: getTopProducts
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 3
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /api/v1/product/{productId}:
    get:
      tags:
        - ProductController
      summary: 상품 조회
      description: 상품을 조회한다.
      operationId: getProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 상품 조회 성공
          content:
            application/json:
              schema:
                type: string
        '404':
          description: 상품을 찾을 수 없습니다.
          content:
            application/json: {}
  /api/v1/coupons/{userId}:
    get:
      tags:
        - CouponController
      summary: 쿠폰 조회
      description: 사용자의 쿠폰목록을 조회힌다.
      operationId: getUserCoupons
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 쿠폰 목록 조회 성공
          content:
            application/json:
              schema:
                type: string
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json: {}
  /api/v1/balances/{userId}:
    get:
      tags:
        - BalanceController
      summary: 잔액 조회
      description: 특정 사용자의 잔액을 조회합니다.
      operationId: getUserBalance
      parameters:
        - name: userId
          in: path
          description: 사용자 ID
          required: true
          schema:
            type: integer
            format: int64
          example: 1
      responses:
        '200':
          description: 잔액 조회 성공
          content:
            application/json:
              schema:
                type: string
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json: {}
components:
  schemas:
    PaymentRegisterV1:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        issuedCouponId:
          type: integer
          format: int64
    OrderProductRegisterV1:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int64
    OrderRegisterV1:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderProductRegisterV1'
    CouponRegisterV1:
      type: object
      properties:
        userId:
          type: integer
          description: 사용자 ID
          format: int64
          example: 1
        couponId:
          type: integer
          description: 쿠폰 ID
          format: int64
          example: 1
      description: 쿠폰 조회 요청 데이터
      example:
        userId: 1
        couponId: 1
    BalanceRegisterV1:
      type: object
      properties:
        userId:
          type: integer
          description: 사용자 ID
          format: int64
          example: 1
        amount:
          type: integer
          description: 충전할 금액
          format: int64
          example: 5000
      description: 잔액 충전 요청 데이터
      example:
        userId: 1
        amount: 5000
